development:
  adapter: postgresql
  encoding: unicode
  database: restaurant_episode_6_development
  pool: 5
  username: syn857
  password:
  timeout: 5000


test:
  adapter: postgresql
  encoding: unicode
  database: restaurant_episode_6_development
  pool: 5
  username: syn857
  password:
  timeout: 5000
